<?php

/**
 * @file
 * Bootstrap Barrio sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_theme_suggestions_views_view_alter().
 */
function my_custom_theme_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];

  $suggestions[] = sprintf(
    'views_view__%s__%s',
    $view->id(),
    str_replace('-', '_', $view->current_display)
  );
}
