<?php

/**
 * @file
 * Bootstrap Barrio sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_theme_suggestions_views_view_alter().
 */
function my_custom_theme_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];

  $suggestions[] = sprintf(
    'views_view__%s__%s',
    $view->id(),
    str_replace('-', '_', $view->current_display)
  );
}

/**
 * Implements hook_preprocess_field().
 */
function my_custom_theme_preprocess_field(array &$variables) {
  if (
    $variables['element']['#field_name'] === 'field_image' &&
    $variables['element']['#entity_type'] === 'commerce_store'
  ) {
    foreach ($variables['items'] as &$item) {
      if (isset($item['content']['#item'])) {
        // fit image to the container.
        $item['content']['#item_attributes']['class'][] = 'img-fluid';
      }
    }
  }
}
