<?php

use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;

use Drupal\Core\Session\AccountInterface;

use Drupal\my_custom_module\App;

/**
 * Handy wrapper around App::instance().
 *
 * @return Drupal\my_custom_module\App
 *   The App singleton.
 */
function app() : App {
  return App::instance();
}

/**
 * Implements hook_cron().
 */
function my_custom_module_cron() {
  App::instance()->hookCron();
}

function my_custom_module_preprocess_page(&$variables) {
  $variables['elements']['#title'] = [
    'type' => '#markup',
    'markup' => 'Hello, world!',
  ];
}

/**
 * Implements hook_form_alter().
 */
function my_custom_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  App::instance()->hookFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_field_access().
 */
function my_custom_module_entity_field_access(
  $operation,
  FieldDefinitionInterface $field_definition,
  AccountInterface $account,
  ?FieldItemListInterface $items = NULL
) {
  return App::instance()->hookEntityFieldAccess(
    $operation,
    $field_definition,
    $account,
    $items
  );
}

/**
 * Implements hook_theme().
 */
function my_custom_module_theme($existing, $type, $theme, $path) {
  return App::instance()->hookTheme();
}

function my_custom_module_theme_registry_alter(&$theme_registry) {
  $theme_registry['commerce_cart_block']['variables']['cart_total'] = NULL;
}

function my_custom_module_preprocess_menu__main(&$variables) {
  App::instance()->hookPreprocessMenuMain($variables);
}

/**
 * Implements hook_preprocess_commerce_store().
 */
function my_custom_module_preprocess_commerce_store(array &$variables) {
  App::instance()->hookPreprocessCommerceStore($variables);
}
