<?php

/**
 * Implements hook_entity_form_display_alter().
 */
/**
function commerce_store_config_entity_form_display_alter(&$form_display, $context) {
  if ($context['entity_type'] === 'commerce_store') {
    $form_display->setComponent('field_google_sheet_url', [
      'type' => 'link_default',
      'weight' => 10,
    ]);

    $form_display->setComponent('field_google_sheet_tab', [
      'type' => 'string_textfield',
      'weight' => 11,
    ]);
  }
}
*/

// use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
/**
function commerce_store_config_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'commerce_store_edit_form' || $form_id === 'commerce_store_add_form') {
    if (isset($form['field_google_sheet_url']['widget'][0]['title'])) {
      $form['field_google_sheet_url']['widget'][0]['title']['#access'] = FALSE;
    }
  }
}
*/