login:
  authenticated:
    redirect_url: ''
    weight: '-10'
  content_editor:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  buyer:
    redirect_url: /buyer-login-redirect
    weight: '-10'
logout:
  authenticated:
    redirect_url: ''
    weight: '-10'
  content_editor:
    redirect_url: ''
    weight: '-10'
  administrator:
    redirect_url: ''
    weight: '-10'
  buyer:
    redirect_url: ''
    weight: '-10'
ignore:
  - '/user/reset/*'
ignore_for:
  login: login
  logout: 0
