display:
  default:
    display_options:
      fields:
        name:
          label: Nom
        operations:
          label: Actions
      filters:
        name:
          expose:
            label: Nom
