display:
  default:
    display_options:
      fields:
        name:
          label: "Nom d'utilisateur"
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Filtrer
